services:
  - type: web
    name: yogabot
    env: java
    plan: free
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/YogaBot-1.0-SNAPSHOT.jar
    autoDeploy: true

    envVars:
      - key: BOT_USERNAME
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m -XX:+UseContainerSupport

    healthCheckPath: /health